### ISSUE TITLE
2018 general election precinct return problems

### ISSUE THREAD

**Issue by agadjanian** [openelections/openelections-data-ky#12]
In the raw data for Kentucky’s 2018 general elections, there’s multiple occurrences of candidates for US House appearing with US Senate listed in the office column. This includes candidates like Seth Hall and Thomas Massie- where they are listed as US House in some parts of the data and US Senate in others.

**Comment by dwillis** [comment]
@agadjanian Thanks - I found this to the be the case in Boyd and Campbell counties, and we've fixed those and the statewide CSV.

**Comment by agadjanian** [comment]
@dwillis ah okay great, thanks for clarifying, I must've downloaded a pre-fixed version.
