### ISSUE TITLE
Incomplete state house precinct data for Todd county.

### ISSUE THREAD

**Issue by benjamin0** [openelections/openelections-data-ky#13]
Looking at [20181106__ky__general__precinct.csv](https://github.com/openelections/openelections-data-ky/blob/master/2018/20181106__ky__general__precinct.csv), it's missing the state house precinct results from Todd county, but it does have the US House data. However, the state house data is in [20181106__ky__general__todd__precinct.csv](https://github.com/openelections/openelections-data-ky/blob/master/2018/counties/20181106__ky__general__todd__precinct.csv) and looks complete. Which script is used to map that data into the 20181106__ky__general__precinct.csv file? Is it just concatenated into the master file?

This might an issue for a few other counties.

**Comment by dwillis** [comment]
@benjamin0 thanks, Ben! We've fixed this issue and confirmed that it doesn't exist for other counties.

**Comment by benjamin0** [comment]
thanks @dwillis!
