### ISSUE TITLE
Precinct result discrepancy between state unofficial results and Clarity Elections data

### ISSUE THREAD

**Issue by benjamin0** [openelections/openelections-data-ky#14]
It looks like there's a discrepancy between the unofficial results from the ky.gov website and unofficial results from Clarity Elections.

For example, for the 9th State Representative District election in 2018, according to [the certified results](https://elect.ky.gov/results/2010-2019/Documents/2018GeneralElectionCertified.pdf), Myron B. Dossett received `3665` votes from Hopkins county. 

However, adding up the data in [the Hopkins county results](https://github.com/openelections/openelections-data-ky/blob/master/2018/counties/20181106__ky__general__hopkins__precinct.csv) only shows `2828` votes. Looks like [this was the original source](https://elect.ky.gov/results/2010-2019/PublishingImages/46199_20181130_RECAP.pdf) for this data.

However, the [unofficial data from Clarity Elections](https://results.enr.clarityelections.com/KY/Hopkins/92051/217951/Web01/en/summary.html#) shows results from precincts `D026`, `D027`, `D028` which the state's unofficial results don't even include. I'm not sure why these are missing, but including the data from these precincts brings the total to `3665` which is the official vote total from Hopkins county.

![image](https://user-images.githubusercontent.com/6760058/64441891-9fb14980-d083-11e9-9ab6-8887be288bee.png)

@dwillis I'm not sure the best way to fix this, but thought I would flag it.

**Comment by dwillis** [comment]
@benjamin0 thanks - very helpful. I suppose the way to go is to use the Clarity data since that matches the certified results. We'll fix.

**Comment by dwillis** [comment]
@benjamin0 We've replaced Hopkins in both the `counties` directory and in the statewide general precinct file.

**Comment by benjamin0** [comment]
Awesome, thanks @dwillis!
