### ISSUE TITLE
Missing 2018 data from Hardin county.

### ISSUE THREAD

**Issue by benjamin0** [openelections/openelections-data-ky#15]
Some candidates/races from Hardin county are missing in the [parsed Hardin 2018 precinct results](https://github.com/openelections/openelections-data-ky/blob/master/2018/counties/20181106__ky__general__hardin__precinct.csv). Looking at the [source data](https://elect.ky.gov/results/2010-2019/PublishingImages/46146_20181130_RECAP.pdf), it looks like some candidates were parsed like (`S Brett Guthrie`, `Hank Linderman`, etc), but some candidates were missing (`Jim DuPlessis`, `Tom Williamson`, etc).

@dwillis

**Comment by dwillis** [comment]
@benjamin0 thanks - we've replaced Hardin.
