### ISSUE TITLE
20181106 general precinct file has inconsistent columns

### ISSUE THREAD

**Issue by warwickmm** [openelections/openelections-data-ky#24]
[2018/20181106__ky__general__precinct.csv](https://github.com/openelections/openelections-data-ky/blob/70aea2998f0665354dfc1934a78d1a56d95c58ba/2018/20181106__ky__general__precinct.csv) has a header with 13 columns
```
county,precinct,office,district,candidate,party,votes,eslate,escan,absentee_mail,absentee,absentee_eslate,absentee_escan
```
However, there are many lines with an inconsistent number of columns.  For example:

Line 30921 only has 7 columns
```
Franklin,AB,Ballots Cast,,,,1214
```
Line 7380 has 1 column and line 7381 has 12 columns, due to a line break
```
Marshall,"A101 South
Benton",U.S. House,1,James R Comer,REP,388,,,,,,
```

**Comment by bmrnjw** [comment]
I wrote a C# console app that read in the file, replaced the occasional imbedded newline with a space, and rewrote the file with a consistent number of columns. I also noticed in the QC of the new file that the original csv had 317 rows with the candidate and party columns interchanged; this was corrected. I think this should be good now.
