### ISSUE TITLE
Can we match candidate parties to pre-processed results files?

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ky#4]
The 2016 general precinct results file has no values for candidate parties, because the information isn't in the general election results produced by the state. Can we extract candidate names from the [primary results](http://elect.ky.gov/results/2010-2019/Documents/2016%20primary%20election%20results.pdf) and match them to the general results to populate the parties?

**Comment by bmrnjw** [comment]
I'll use the following 3 letter codes for party:
REP - Republican
DEM - Democrat
LBT - Libertarian
GRN - Green
CON - Constitution
IND - Independent
SWK - Soc Wk
REF - Reform

The programmatic approach will be a bit different than relying only on the primaries for party affiliation (some candidates will not have competed in primaries)

**Comment by bmrnjw** [comment]
files updated
