### ISSUE TITLE
2016 general election precinct results errors

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ky#5]
Underreported in precincts:

- [x] Breckinridge
- [x] Hart
- [x] Mercer

 and it looks like some provisional votes are not included in the official totals for Jefferson.

### Replace

- [x] Jefferson County 2016 general results has 0 votes for everyone. Convert [this PDF](https://github.com/openelections/openelections-sources-ky/blob/master/2016/Jefferson%20KY%20Gen16OfficialSOVC.pdf) using [Tabula](http://tabula.technology/) into a CSV file that matches the other KY precinct files ([here's an example](https://github.com/openelections/openelections-data-ky/blob/master/2016/20161108__ky__general__campbell__precinct.csv)).

### Missing

Convert the PDF files located [here](https://github.com/openelections/openelections-sources-ky/tree/master/2016/recap_sheets) for the following counties into CSV files matching our format ([here's an example](https://github.com/openelections/openelections-data-ky/blob/master/2016/20161108__ky__general__campbell__precinct.csv)).

- [x] Campbell
- [x] Warren
- [x] Breckinridge
- [x] Elliott
- [x] Hart
- [x] Lee
- [x] Lewis
- [x] Mercer
- [x] Morgan
- [x] Owsley
- [x] Powell
- [x] Robertson
- [x] Wolfe

### Discrepancies

Compared to the state's official count, the file has 6 fewer votes in Fayette, 1 fewer in Hardin, 1 fewer in Kenton, 1 more in Menifee, 1 fewer in Nelson, 13 fewer in Pike, 2 fewer in Pulaski, 2 fewer in Scott, 3 fewer in Trigg, 1 fewer in Wayne.

**Comment by rkahne** [comment]
I have this data for all counties in Kentucky, but I don't know the format you need it.  Do you have an example CSV for what it should look like?

**Comment by dwillis** [comment]
Hi @rkahne, thanks! Here's an example from this repository: https://github.com/openelections/openelections-data-ky/blob/master/2016/20161108__ky__general__campbell__precinct.csv

**Comment by rkahne** [comment]
@dwillis I made a pull request.

**Comment by rkahne** [comment]
@dwillis I redid the work by scraping the PDF you provided.  If there are other PDFs similar to the Jefferson County one, the R Script I also added could be useful in scraping those as well.
