### ISSUE TITLE
County-level results from 2018 Primary

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ky#9]
Unfortunately, the [PDF posted by the Secretary of State](https://elect.ky.gov/results/Documents/June%205%202018%20Certification.pdf) appears to be an image, so OCR might be necessary here.

Header row for the output CSV (`20180522__ky__primary__county.csv`) is:

`county`, `office`, `district`, `party`, `candidate`, `votes`

For the following contests: U.S. Representative, State Senator, State Representative

The file should look something like this:

https://github.com/openelections/openelections-data-ky/blob/master/2016/20160517__ky__primary__county.csv

**Comment by timtrice** [comment]
I canl knock this one out.

**Comment by dwillis** [comment]
Awesome, thanks @timtrice!
